import Head from "next/head";
import Card from "react-animated-3d-card";
import Link from "next/link";
import { Endpoint } from "../services/endpoint";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>API Filmes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to API Filmes</h1>

        <div className={styles.grid}>
          {Endpoint.map((end, index) => (
            // <a className={styles.card}>
            <Link
              key={index}
              href={end.endpoint}
              target="_blank"
              rel="noopener noreferrer"
              className={styles.card}
            >
              <Card
                cursorPointer={false}
                shineStrength={0.75}
                style={{
                  background:
                    "linear-gradient(to right, #0f0c29, #302b63, #24243e)",
                  width: "13rem",
                  height: "11rem",
                  cursor: "pointer",
                }}
                onClick={() => console.log()}
              >
                <h2>{end.title}</h2>
                <p>{end.text}</p>
              </Card>
            </Link>
            // </a>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/Peedrohenrique"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by: Pedro Henrique
        </a>
      </footer>
    </div>
  );
}
